const data = [
	{
		id: 1,
		name: "Agra",
		info: "Agra is a city in northern India, known for the iconic Taj Mahal, a stunning white marble mausoleum built by Mughal emperor Shah Jahan in memory of his beloved wife. Agra is also home to several other historic and architectural wonders, including Agra Fort and Fatehpur Sikri.",
		image: "https://cdn.thecodehelp.in/Agra.jpeg",
		price: "55,758",
	},
	{
		id: 2,
		name: "Jaipur",
		info: `Jaipur is the capital city of the Indian state of Rajasthan, known for its stunning pink-hued buildings and palaces. The city is also known as the "Pink City" due to the color of many of its buildings. Jaipur is famous for its intricate textiles, colorful handicrafts, and delicious cuisine.`,
		image: "https://cdn.thecodehelp.in/Jaipur.jpeg",
		price: "82,560",
	},
	{
		id: 3,
		name: "Goa",
		info: " Goa is a small state on India's western coast, known for its stunning beaches, vibrant nightlife, and Portuguese-influenced architecture. The state is also known for its spicy seafood dishes and unique cultural traditions.",
		image: "https://cdn.thecodehelp.in/Goa.jpeg",
		price: "69,695",
	},
	{
		id: 4,
		name: "Varanasi",
		info: "Varanasi is a holy city in northern India, situated on the banks of the sacred river Ganges. The city is a major pilgrimage site for Hindus and is famous for its ancient temples, winding alleyways, and colorful festivals.",
		image: "https://cdn.thecodehelp.in/Varanasi.jpeg",
		price: "71,095",
	},
	{
		id: 5,
		name: "Darjeeling",
		info: "Starting in the colorful port city of Gdańsk, you'll escape the crowds and embrace the understated elegance of ready-for-prime-time Poland for 10 days. With an expert Rick Steves guide at your side, you'll experience mighty Malbork castle, the cobbly-cute village of Toruń, Poland's contemporary capital of Warsaw, the spiritual Jasna Góra Monastery, and charming Kraków — Poland's finest city. In this land of surprises — so trendy and hip, yet steeped in history — there's so much to discover. Join us for the Best of Poland in 10 Days!",
		image: "https://cdn.thecodehelp.in/Darjeeling.jpeg",
		price: "78,595",
	},
	{
		id: 6,
		name: "Jaisalmer",
		info: "Jaisalmer is a city in the Indian state of Rajasthan, known for its stunning sandstone architecture and its location in the heart of the Thar Desert. The city is home to several impressive palaces and fortresses, as well as unique cultural traditions and handicrafts.",
		image: "https://cdn.thecodehelp.in/Jaisalmer.jpeg",
		price: "67,355",
	},
	{
		id: 7,
		name: "Prayagraj",
		info: "Prayagraj is one of the oldest cities in India. It is crowned in ancient scriptures as 'Prayag' or 'Teertharaj' and is considered the holiest of pilgrimage centres of India. Prayagraj is the seat of Allahabad High Court, the highest judicial body in the state of Uttar Pradesh. The city is known as the 'Prime Minister Capital of India'",
		image: "https://www.adotrip.com/public/images/city/5c3f117f307c4-Allahabad%20Trip.jpg",
		price: "98,595",
	},
	{
		id: 8,
		name: "Kochi",
		info: "Kochi is a port city in the Indian state of Kerala, known for its historic connections to trade and commerce. The city is home to several stunning churches, synagogues, and mosques, as well as a rich culinary tradition that blends Indian, Portuguese, and other influences.",
		image: "https://cdn.thecodehelp.in/Kochi.jpeg",
		price: "68,595",
	},
	{
		id: 9,
		name: "Delhi",
		info: "Delhi is the capital city of India and is regarded as the heart of the nation. The city is popular for its enriched culture and heritage. The city hosts some famous historical monuments and is developing with the passing of time. Delhi is on the banks of the Yamuna River. Historians have evidence that people have been living in this region since at least the 6th century BC. The India Gate is a war memorial in Delhi.",
		image: "https://s4.scoopwhoop.com/anj2/5d88ad6450758d655edc1e2d/23079bdb-6ea5-464f-a4ed-cdbb07ac9057.jpg",
		price: "58,694",
	},
	{
		id: 10,
		name: "Ayodhya",
		info: "Ayodhya is a city situated on the banks of holy river Saryu in the Indian state of Uttar Pradesh. It is the administrative headquarters of Faizabad district and the Faizabad division of Uttar Pradesh, India. The legendary city of Ayodhya, popularly identified as the present-day Ayodhya, is the birthplace of the Hindu deity Rama of Kosala and setting of the great epic Ramayana and its many versions.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Sarayu_River_night_view%2C_Ayodhya_001.jpg/1920px-Sarayu_River_night_view%2C_Ayodhya_001.jpg",
		price: "64,875",
	},
	{
		id: 11,
		name: "Bangalore",
		info: "Bangalore, officially Bengaluru, is the capital and largest city of the southern Indian state of Karnataka. Having evolved gradually from being the Garden city to the Silicon Valley of India, Bangalore is India's third-largest city. Bangalore is loved for its pleasant weather, beautiful parks and the many lakes here.",
		image: "https://www.tourist-destinations.com/wp-content/uploads/2013/04/Bangalore-Palace.jpg",
		price: "85,635",
	},
	{
		id: 12,
		name: "Kolkata",
		info: "Kolkata is the capital of West Bengal, Kolkata is one of the four metropolitan cities in India. Located on the eastern bank of the Hooghly River, the city is approximately 80 kilometres west of the border with Bangladesh. Known as the 'City of Joy', Kolkata holds an important place in the economy, politics and culture of India.",
		image: "https://static.toiimg.com/photo/48355930/.jpg",
		price: "76,565",
	},
	{
		id: 13,
		name: "Amritsar",
		info: "Amritsar is the second-largest city and district of Punjab. It is also one of the fastest-growing cities of Punjab. Amritsar is home to the spectacular Golden Temple, Sikhism's holiest shrine and one of India’s most serene and humbling sights.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Golden_Temple_Amritsar_Gurudwara_%28cropped%29.jpg/1920px-Golden_Temple_Amritsar_Gurudwara_%28cropped%29.jpg",
		price: "76,565",
	},
	{
		id: 14,
		name: "Kashmir",
		info: "Kashmir is the northernmost geographical region of the Indian subcontinent. Kashmir is an ethnically diverse Himalayan region, covering around 86,000 sq miles ( 222,738 sq km), and famed for the beauty of its lakes, meadows and snow-capped mountains.",
		image: "https://www.worldatlas.com/r/w1200-q80/upload/70/33/ab/shutterstock-115227475.jpg",
		price: "83,937",
	},
	{
		id: 15,
		name: "Raebareli",
		info: "Raebareli is a city in Indian state of Uttar Pradesh. It is the administrative headquarters of Raebareli district and a part of Lucknow Division. The city is situated on the banks of the Sai river, 82 km southeast of Lucknow. The city is situated on the banks of the Sai river,[3] 82 km (51 mi) southeast of Lucknow. It possesses many architectural features and sites, chief of which is a strong and spacious fort.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Collage_Places_in_Raebareli.jpg/800px-Collage_Places_in_Raebareli.jpg",
		price: "21,376",
	},
];

export default data;
